# Generated by Django 4.2 on 2023-04-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('surname',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('genre', models.CharField(choices=[('fantasy', 'fantasy'), ('comedy', 'comedy'), ('drama', 'drama'), ('horror', 'horror'), ('popular science', 'popular science')], max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('authors', models.ManyToManyField(to='task2.author')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
