# Generated by Django 4.2 on 2023-05-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70)),
                ('content', models.TextField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='task4/media/photos/%Y/%m/%d/')),
                ('score', models.IntegerField(choices=[(1, 'Really bad'), (2, 'Bad'), (3, 'Normal'), (4, 'Well'), (5, 'Perfect')], default=3)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('is_positive', models.BooleanField(default=True, verbose_name='Is it positive review')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-time_create'],
            },
        ),
    ]
