# Generated by Django 4.2.1 on 2023-05-07 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('surname',),
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('genre', models.CharField(choices=[('fantasy', 'fantasy'), ('comedy', 'comedy'), ('drama', 'drama'), ('horror', 'horror'), ('popular science', 'popular science')], max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('pub_date', models.DateField(blank=True, default=None, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.author')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
